config:
  # Plugin Messages Prefix
  prefix: "&6[XStream]"

  titles:
    # Allow the titles?
    allow: true

    # Title Times Parameters (In ticks).
    # In-Coming time.
    fade-in: 20

    # Staying time.
    stay: 60

    # Outing time.
    fade-out: 20